Pharmacy/Controllers/MedicinesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Pharmacy.Domain.Models;
using Pharmacy.Domain.Response;
using Pharmacy.Domain.ViewModels;
using Pharmacy.Domain.ViewModels.Category;
using Pharmacy.Domain.ViewModels.Medecine;
using Pharmacy.Service.Interfaces;
using Pharmacy.Service.Service;

namespace Pharmacy.Controllers;

public class MedicinesController : Controller
{
    private readonly IMedicineService _medicineService;
    private IMapper _mapper { get; set; }

    MapperConfiguration mapperConfiguration = new MapperConfiguration(p => { p.AddProfile<AppMappingProfile>(); });

    public MedicinesController(IMedicineService medicineService)
    {
        _medicineService = medicineService;
        _mapper = mapperConfiguration.CreateMapper();
    }

    public IActionResult ListOfMedicines(Guid Id)
    {
        var result = _medicineService.GetAllMedicinesByIdCategory(Id);
        ListOfMedicinesViewModel listMedicines = new ListOfMedicinesViewModel
        {
            Medicines = _mapper.Map<List<MedicinesForListOfMedicinesViewModel>>(result.Data),
            CategoryId = Id
        };
        return View(listMedicines);
    }

    [HttpPost]
    public async Task<IActionResult> Filter([FromBody] MedicineFilter filter)
    {
        var result = _medicineService.GetMedicinesByFilter(filter);
        var filteredMedicines = _mapper.Map<List<MedicinesForListOfMedicinesViewModel>>(result.Data);
        return Json(filteredMedicines);
    }


    public async Task<IActionResult> MedicinePage(Guid Id)
    {
        var resultMedicine = await _medicineService.GetMedicinesById(Id);
        MedicinePageViewModel medicine = _mapper.Map<MedicinePageViewModel>(resultMedicine.Data);
        return View(medicine);
    }


}

Pharmacy/Views/Medicines/ListOfMedicines.cshtml
@using Org.BouncyCastle.Crypto.Engines
@model Pharmacy.Domain.ViewModels.Medecine.ListOfMedicinesViewModel

@{
Layout = "_Layout";
ViewData["Title"] = "Список медикаментов";
}
<link rel="stylesheet" href="~/css/filter.css" asp-append-version="true"/>

<div class="catalog-section">
    <div class="content-container">
        <!-- Секция категорий -->
        <aside class="categories-section">
            <div class="sort-container">
                <!-- Сортировка -->
                <label for="sort-options" class="sort-label">Сортировать по:</label>
                <select id="sort-options" class="sort-select">
                    <option value="">Выберите...</option>
                    <option value="price-adult-asc">Цена (по возрастанию)</option>
                    <option value="price-adult-desc">Цена (по убыванию)</option>
                </select>
            </div>
            <h3 class="filter-title">Фильтр</h3>
            <!-- Фильтр для цен -->
            <div class="filter-price">
                <label class="filter-label">Цена:</label>
                <div>
                    <label for="adult-min-price">Минимальная цена:</label>
                    <input type="range" id="adult-min-price" min="0" max="1000" value="0">
                    <span id="adult-min-label">0</span>
                </div>
                <div>
                    <label for="adult-max-price">Максимальная цена:</label>
                    <input type="range" id="adult-max-price" min="0" max="599" value="599">
                    <span id="adult-max-label">599</span>
                </div>
                <div>Текущие значения: <span id="adult-price-values">0 - 599</span></div>
            </div>
            <input id="CategoryId" value="@Model.CategoryId" style="display: none"/>
            <input type="text" id="search-input" placeholder="Введите название товара">
            <div class="filter-button">
                <button id="apply-filter" class="filter-apply">Применить фильтр</button>
            </div>
        </aside>
       
        <!-- Секция каталога -->
        <main id="catalog" class="catalog-section catalog-product">
            <div class="catalog-grid">
                @foreach (var item in Model.Medicines)
                {
                    <div class="product-card">
                        <!-- Изображение -->
                        <div class="product-img-container">
                            <img src="@item.Image" class="product-img" alt="Medicine Image"/>
                        </div>

                <!-- Информация о медикаменте -->
                <h2 class="product-title">@item.Name</h2>

                <!-- Цена -->
                <div class="product-price">
                    @item.Price₽
                </div>

                <!-- Кнопка подробнее -->
                <div class="product-details">
                    <button class="details-button"
                            onclick="window.location.href='@Url.Action("MedicinePage", "Medicines", new { Id = item.Id })'">
                        Подробнее
                    </button>
                </div>

                        <!-- Скрытые поля -->
                        <input asp-for="@item.Id" value="@item.Id" type="hidden"/>
                        <input asp-for="@item.CategoryId" value="@item.CategoryId" type="hidden"/>
                    </div>
                }
            </div>
        </main>
    </div>
</div>

Pharmacy/Views/Medicines/MedicinePage.cshtml
@model Pharmacy.Domain.ViewModels.MedicinePageViewModel
@{
    ViewData["Title"] = @Model.Name;
    Layout = "_Layout";
}

<link rel="stylesheet" href="~/css/filter.css" asp-append-version="true"/>
<div class="product">
    <div class="product-details">
        <div class="product-images">
            <img id="main-image" src="@Model.Image" alt="@Model.Name" class="main-image">
        </div>
        <div class="product-info">
            <h1>@Model.Name</h1>
            <p class="product-price">@Model.Price ₽</p>
            <div class="product-actions">
                <button class="btn btn-buy">Купить</button>
                <button class="btn btn-add-to-cart">Добавить в корзину</button>
            </div>
        </div>
    </div>
    <div class="product-description">
        <p><strong>Описание:</strong> @Model.Description</p>
    </div>
</div>з